In [1]:
import numpy as np
import pandas as pd

In [2]:
obj = pd.Series([4, 7, -5, 3])

display(obj)

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj[obj > 4]

1    7
dtype: int64

In [4]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)

print(df)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [5]:
df_from_csv = pd.read_csv('https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv')
df_from_csv

     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]

In [6]:
# df['year'] = 1947
# print(df)

In [7]:
df['pop'] = np.arange(len(df))

print(df)

    state  year  pop
0    Ohio  2000    0
1    Ohio  2001    1
2    Ohio  2002    2
3  Nevada  2001    3
4  Nevada  2002    4
5  Nevada  2003    5

In [8]:
df1 = pd.DataFrame({
        "gender": ["Male", "Female", "Female", "Male"],
        "product": ["Book", "Electronics", "Book", "Clothing"]
})
print(df1["gender"].dtype)

object

In [9]:
df1[['gender']]

   gender
0    Male
1  Female
2  Female
3    Male

In [10]:
df.loc[[0,3]]

    state  year  pop
0    Ohio  2000    0
3  Nevada  2001    3

In [11]:
df.iloc[0,2]

np.int64(0)

In [12]:
df2 = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

print(df2)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [13]:
print(df2.loc[["Ohio","Utah"]])

      one  two  three  four
Ohio    0    1      2     3
Utah    8    9     10    11

In [14]:
print(df.loc[:,['year','pop']])

   year  pop
0  2000    0
1  2001    1
2  2002    2
3  2001    3
4  2002    4
5  2003    5

In [15]:
df2.iloc[[1,0]]

          one  two  three  four
Colorado    4    5      6     7
Ohio        0    1      2     3

In [16]:
print(df[df['pop'] > 2])

    state  year  pop
3  Nevada  2001    3
4  Nevada  2002    4
5  Nevada  2003    5

In [17]:
data = {"state": ["Ohio", "New York", "Ohio", "Nevada", "Chicago", "Califonia"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df3 = pd.DataFrame(data)

print(df3)

       state  year  pop
0       Ohio  2000  1.5
1   New York  2001  1.7
2       Ohio  2002  3.6
3     Nevada  2001  2.4
4    Chicago  2002  2.9
5  Califonia  2003  3.2

In [18]:
df3[df3['state'].str.contains('hi')]

     state  year  pop
0     Ohio  2000  1.5
2     Ohio  2002  3.6
4  Chicago  2002  2.9

In [19]:
df3['pop'] > 2

0    False
1    False
2     True
3     True
4     True
5     True
Name: pop, dtype: bool

In [20]:
df3[~(df3['pop'] > 2)]

      state  year  pop
0      Ohio  2000  1.5
1  New York  2001  1.7

In [26]:
df = pd.DataFrame(
    [
      [1.4, np.nan],
      [7.1, -4.5],
      [np.nan, np.nan],
      [0.75, -1.3]
    ],
    columns=["one", "two"])

print(df)

    one  two
0  1.40  NaN
1  7.10 -4.5
2   NaN  NaN
3  0.75 -1.3

In [28]:
df4 = pd.DataFrame(np.random.standard_normal((4, 3)),
                  columns=list("bde"),
                  index=["Utah", "Ohio", "Texas", "Oregon"])
print(df4)

               b         d         e
Utah   -0.075085 -1.033623 -0.447585
Ohio   -1.584003  0.989415 -1.601848
Texas  -1.470183  0.543433 -1.416656
Oregon -0.776214  0.129647  0.510025

In [29]:
def f1(x):
    return x.max() - x.min()

print(df4.apply(f1))

b    1.508918
d    2.023038
e    2.111872
dtype: float64

In [31]:
print(df4.apply(f1, axis="columns"))

Utah      0.958538
Ohio      2.591263
Texas     2.013616
Oregon    1.286239
dtype: float64

In [33]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

print(df4.apply(f2))

            b         d         e
min -1.584003 -1.033623 -1.601848
max -0.075085  0.989415  0.510025

In [35]:
print(df4.describe())

              b         d         e
count  4.000000  4.000000  4.000000
mean  -0.976371  0.157218 -0.739016
std    0.698915  0.868058  0.974459
min   -1.584003 -1.033623 -1.601848
25%   -1.498638 -0.161170 -1.462954
50%   -1.123199  0.336540 -0.932120
75%   -0.600932  0.654929 -0.208183
max   -0.075085  0.989415  0.510025