In [38]:
import pandas as pd
import numpy as np

In [39]:
# Task 1: Create a DataFrame
data = {"total_bill": [16.99, 10.34, 21.01, 23.68, 24.59],
        "tip": [1.01, np.nan, 3.5, 3.31, 3.61],
        "smoker": ["No", "No", "Yes", np.nan, "No"], 
        "day": ["Sun", None, "Mon", "Wed", "Sat"],
        "time": ["Dinner", "Dinner", None, "Dinner", "Lunch"],
        "size": [2, 3, 3, 2, np.nan],
       }
df = pd.DataFrame(data)

df

   total_bill   tip smoker   day    time  size
0       16.99  1.01     No   Sun  Dinner   2.0
1       10.34   NaN     No  None  Dinner   3.0
2       21.01  3.50    Yes   Mon    None   3.0
3       23.68  3.31    NaN   Wed  Dinner   2.0
4       24.59  3.61     No   Sat   Lunch   NaN

In [40]:
# T2-1: Select 'tip' column using df[column].
result2_1 = df['tip']
result2_1

0    1.01
1     NaN
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [41]:
# T2-2: Select 'size','tip','day' columns using df[column].
result2_2 = df[['size', 'tip', 'day']]
print(result2_2)

   size   tip   day
0   2.0  1.01   Sun
1   3.0   NaN  None
2   3.0  3.50   Mon
3   2.0  3.31   Wed
4   NaN  3.61   Sat

In [42]:
# T2-3: Select 'tip','size','day' columns using df.loc[:, cols].
result2_3 = df.loc[:,['tip', 'size', 'day']]
print(result2_3)

    tip  size   day
0  1.01   2.0   Sun
1   NaN   3.0  None
2  3.50   3.0   Mon
3  3.31   2.0   Wed
4  3.61   NaN   Sat

In [43]:
# T2-4: Select 'time','smoker','day' columns using df.iloc[:, cols].
result2_4 = df.iloc[:,[4, 2, 3]]
print(result2_4)

     time smoker   day
0  Dinner     No   Sun
1  Dinner     No  None
2    None    Yes   Mon
3  Dinner    NaN   Wed
4   Lunch     No   Sat

In [45]:
# T3-1: Select rows with tip > 2 via df[condition]. Store your answer in result3_1.
result3_1 = df[df['tip'] > 2]
print(result3_1)

   total_bill   tip smoker  day    time  size
2       21.01  3.50    Yes  Mon    None   3.0
3       23.68  3.31    NaN  Wed  Dinner   2.0
4       24.59  3.61     No  Sat   Lunch   NaN

In [49]:
# T3-2: Select rows with index 1, 3 via df.iloc[list_of_indices]
result3_2 = df.iloc[[1, 3]]
print(result3_2)

   total_bill   tip smoker   day    time  size
1       10.34   NaN     No  None  Dinner   3.0
3       23.68  3.31    NaN   Wed  Dinner   2.0

In [50]:
# T3-3: Select rows with label 1, 3 via df.loc[list_of_labels]
result3_3 = df.loc[[1, 3]]
print(result3_3)

   total_bill   tip smoker   day    time  size
1       10.34   NaN     No  None  Dinner   3.0
3       23.68  3.31    NaN   Wed  Dinner   2.0

In [51]:
# T4: Use pd.read_csv to read the local tips.csv file into a DataFrame named df.
df = pd.read_csv('tips.csv')
df

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [68]:
# T5-1: Select tipping data on Friday. Store your answer in result5_1.
result5_1 = df.loc[df['day'] == 'Fri']
print(result5_1)

     total_bill   tip smoker  day    time  size
90        28.97  3.00    Yes  Fri  Dinner     2
91        22.49  3.50     No  Fri  Dinner     2
92         5.75  1.00    Yes  Fri  Dinner     2
93        16.32  4.30    Yes  Fri  Dinner     2
94        22.75  3.25     No  Fri  Dinner     2
95        40.17  4.73    Yes  Fri  Dinner     4
96        27.28  4.00    Yes  Fri  Dinner     2
97        12.03  1.50    Yes  Fri  Dinner     2
98        21.01  3.00    Yes  Fri  Dinner     2
99        12.46  1.50     No  Fri  Dinner     2
100       11.35  2.50    Yes  Fri  Dinner     2
101       15.38  3.00    Yes  Fri  Dinner     2
220       12.16  2.20    Yes  Fri   Lunch     2
221       13.42  3.48    Yes  Fri   Lunch     2
222        8.58  1.92    Yes  Fri   Lunch     1
223       15.98  3.00     No  Fri   Lunch     3
224       13.42  1.58    Yes  Fri   Lunch     2
225       16.27  2.50    Yes  Fri   Lunch     2
226       10.09  2.00    Yes  Fri   Lunch     2

In [88]:
# T5-2: Select tipping data on the weekend (i.e., Saturday and Sunday).
result5_2 = df.loc[(df['day'] == 'Sat') | (df['day'] == 'Sun')]
print(result5_2)

     total_bill   tip smoker  day    time  size
0         16.99  1.01     No  Sun  Dinner     2
1         10.34  1.66     No  Sun  Dinner     3
2         21.01  3.50     No  Sun  Dinner     3
3         23.68  3.31     No  Sun  Dinner     2
4         24.59  3.61     No  Sun  Dinner     4
..          ...   ...    ...  ...     ...   ...
238       35.83  4.67     No  Sat  Dinner     3
239       29.03  5.92     No  Sat  Dinner     3
240       27.18  2.00    Yes  Sat  Dinner     2
241       22.67  2.00    Yes  Sat  Dinner     2
242       17.82  1.75     No  Sat  Dinner     2

[163 rows x 6 columns]

In [73]:
# T5-3: From T5-2, show only the 'total_bill' column.
result5_3 = df['total_bill']
print(result5_3)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [79]:
# T5-4: Select tipping data from the tables with a smoker (i.e., df['smoker']=='Yes') and the total bill is less than 10 (i.e., df['total_bill'] < 10).
result5_4 = df.loc[(df['smoker'] == 'Yes') & (df['total_bill'] < 10)]
print(result5_4)

     total_bill   tip smoker  day    time  size
67         3.07  1.00    Yes  Sat  Dinner     1
92         5.75  1.00    Yes  Fri  Dinner     2
172        7.25  5.15    Yes  Sun  Dinner     2
178        9.60  4.00    Yes  Sun  Dinner     2
218        7.74  1.44    Yes  Sat  Dinner     2
222        8.58  1.92    Yes  Fri   Lunch     1

In [81]:
# T5-5: From T5-4: show only the 'tip','size' columns.
result5_5 = df[['tip', 'size']]
print(result5_5)

      tip  size
0    1.01     2
1    1.66     3
2    3.50     3
3    3.31     2
4    3.61     4
..    ...   ...
239  5.92     3
240  2.00     2
241  2.00     2
242  1.75     2
243  3.00     2

[244 rows x 2 columns]

In [89]:
# T6-1: Calculate the mean of the 'total_bill' during the weekend. Store your answer in result6_1.
df_weekend = df.loc[(df['day'] == 'Sat') | (df['day'] == 'Sun')]
result6_1 = df_weekend['total_bill'].mean()
print(result6_1)

20.893006134969326

In [92]:
# T6-2: Calculate the mean of the 'tip' from the tables with a smoker.df_weekend = df.loc[(df['day'] > 'Sat') & (df['day'] == 'Sun')]
df_smoker = df.loc[(df['smoker'] == 'Yes')]
result6_2 = df_smoker['tip'].mean()
print(result6_2)

3.008709677419355

In [93]:
# T6-3: Create a new column, named 'price_per_head', representing the price per head. This can be calculated by dividing the 'total_bill' with the 'size'.
df['price_per_head'] = df['total_bill'] / df['size']
df

     total_bill   tip smoker   day    time  size  price_per_head
0         16.99  1.01     No   Sun  Dinner     2        8.495000
1         10.34  1.66     No   Sun  Dinner     3        3.446667
2         21.01  3.50     No   Sun  Dinner     3        7.003333
3         23.68  3.31     No   Sun  Dinner     2       11.840000
4         24.59  3.61     No   Sun  Dinner     4        6.147500
..          ...   ...    ...   ...     ...   ...             ...
239       29.03  5.92     No   Sat  Dinner     3        9.676667
240       27.18  2.00    Yes   Sat  Dinner     2       13.590000
241       22.67  2.00    Yes   Sat  Dinner     2       11.335000
242       17.82  1.75     No   Sat  Dinner     2        8.910000
243       18.78  3.00     No  Thur  Dinner     2        9.390000

[244 rows x 7 columns]

In [96]:
# T6-4: Calculate the maximum 'price_per_head' on Sunday.
result6_4 = df['price_per_head'].max()
print(result6_4)

20.275

In [98]:
# T7-1: Sort by 'tip' in an ascending order. Store your answer in result7_1.
result7_1 = df.sort_values(by='tip', ascending=True)
print(result7_1)

     total_bill    tip smoker   day    time  size  price_per_head
92         5.75   1.00    Yes   Fri  Dinner     2        2.875000
111        7.25   1.00     No   Sat  Dinner     1        7.250000
67         3.07   1.00    Yes   Sat  Dinner     1        3.070000
236       12.60   1.00    Yes   Sat  Dinner     2        6.300000
0         16.99   1.01     No   Sun  Dinner     2        8.495000
..          ...    ...    ...   ...     ...   ...             ...
141       34.30   6.70     No  Thur   Lunch     6        5.716667
59        48.27   6.73     No   Sat  Dinner     4       12.067500
23        39.42   7.58     No   Sat  Dinner     4        9.855000
212       48.33   9.00     No   Sat  Dinner     4       12.082500
170       50.81  10.00    Yes   Sat  Dinner     3       16.936667

[244 rows x 7 columns]

In [99]:
# T7-2: Sort by 'tip' in descending order.
result7_2 = df.sort_values(by='tip', ascending=False)
print(result7_2)

     total_bill    tip smoker   day    time  size  price_per_head
170       50.81  10.00    Yes   Sat  Dinner     3       16.936667
212       48.33   9.00     No   Sat  Dinner     4       12.082500
23        39.42   7.58     No   Sat  Dinner     4        9.855000
59        48.27   6.73     No   Sat  Dinner     4       12.067500
141       34.30   6.70     No  Thur   Lunch     6        5.716667
..          ...    ...    ...   ...     ...   ...             ...
0         16.99   1.01     No   Sun  Dinner     2        8.495000
111        7.25   1.00     No   Sat  Dinner     1        7.250000
92         5.75   1.00    Yes   Fri  Dinner     2        2.875000
67         3.07   1.00    Yes   Sat  Dinner     1        3.070000
236       12.60   1.00    Yes   Sat  Dinner     2        6.300000

[244 rows x 7 columns]

In [100]:
# T7-3: Sort by 'total_bill' and 'tip' in descending order.
result7_3 = df.sort_values(by=['total_bill', 'tip'], ascending=False)
print(result7_3)

     total_bill    tip smoker   day    time  size  price_per_head
170       50.81  10.00    Yes   Sat  Dinner     3       16.936667
212       48.33   9.00     No   Sat  Dinner     4       12.082500
59        48.27   6.73     No   Sat  Dinner     4       12.067500
156       48.17   5.00     No   Sun  Dinner     6        8.028333
182       45.35   3.50    Yes   Sun  Dinner     3       15.116667
..          ...    ...    ...   ...     ...   ...             ...
149        7.51   2.00     No  Thur   Lunch     2        3.755000
172        7.25   5.15    Yes   Sun  Dinner     2        3.625000
111        7.25   1.00     No   Sat  Dinner     1        7.250000
92         5.75   1.00    Yes   Fri  Dinner     2        2.875000
67         3.07   1.00    Yes   Sat  Dinner     1        3.070000

[244 rows x 7 columns]

In [103]:
# T7-4: Show the 'total_bill', 'tip' and 'price_per_head' columns during the weekend sorted by 'price_per_head' in an ascending order.
df_columns = df[['total_bill', 'tip', 'price_per_head']]
df_weekend = df_columns.loc[(df['day'] == 'Sat') | (df['day'] == 'Sun')]
result7_4 = df_weekend.sort_values(by=['price_per_head'], ascending=True)
print(result7_4)

     total_bill    tip  price_per_head
67         3.07   1.00        3.070000
16        10.33   1.67        3.443333
1         10.34   1.66        3.446667
172        7.25   5.15        3.625000
218        7.74   1.44        3.870000
..          ...    ...             ...
237       32.83   1.17       16.415000
175       32.90   3.11       16.450000
170       50.81  10.00       16.936667
179       34.63   3.55       17.315000
184       40.55   3.00       20.275000

[163 rows x 3 columns]