In [1]:
import numpy as np
import pandas as pd

In [2]:
tips = pd.read_csv("tips.csv")

print(tips)

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [3]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   smoker      244 non-null    object
 3   day         244 non-null    object
 4   time        244 non-null    object
 5   size        244 non-null    int64
dtypes: float64(2), int64(1), object(3)
memory usage: 11.6+ KB

In [4]:
tips["tip_pct"] = tips["tip"] / tips["total_bill"]

print(tips[["total_bill", "tip", "tip_pct"]])

     total_bill   tip   tip_pct
0         16.99  1.01  0.059447
1         10.34  1.66  0.160542
2         21.01  3.50  0.166587
3         23.68  3.31  0.139780
4         24.59  3.61  0.146808
..          ...   ...       ...
239       29.03  5.92  0.203927
240       27.18  2.00  0.073584
241       22.67  2.00  0.088222
242       17.82  1.75  0.098204
243       18.78  3.00  0.159744

[244 rows x 3 columns]

In [5]:
print(tips.groupby("day")["tip_pct"].mean())

day
Fri     0.169913
Sat     0.153152
Sun     0.166897
Thur    0.161276
Name: tip_pct, dtype: float64

In [6]:
tips['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [7]:
tips.groupby('day').size()

day
Fri     19
Sat     87
Sun     76
Thur    62
dtype: int64

In [8]:
by_day = tips.groupby("day")

print(type(by_day))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [9]:
print(by_day.get_group("Sun"))

     total_bill   tip smoker  day    time  size   tip_pct
0         16.99  1.01     No  Sun  Dinner     2  0.059447
1         10.34  1.66     No  Sun  Dinner     3  0.160542
2         21.01  3.50     No  Sun  Dinner     3  0.166587
3         23.68  3.31     No  Sun  Dinner     2  0.139780
4         24.59  3.61     No  Sun  Dinner     4  0.146808
..          ...   ...    ...  ...     ...   ...       ...
186       20.90  3.50    Yes  Sun  Dinner     3  0.167464
187       30.46  2.00    Yes  Sun  Dinner     5  0.065660
188       18.15  3.50    Yes  Sun  Dinner     3  0.192837
189       23.10  4.00    Yes  Sun  Dinner     3  0.173160
190       15.69  1.50    Yes  Sun  Dinner     2  0.095602

[76 rows x 7 columns]

In [10]:
tips.groupby(["day", "smoker", "time"])["tip_pct"].mean()

day   smoker  time
Fri   No      Dinner    0.139622
              Lunch     0.187735
      Yes     Dinner    0.165347
              Lunch     0.188937
Sat   No      Dinner    0.158048
      Yes     Dinner    0.147906
Sun   No      Dinner    0.160113
      Yes     Dinner    0.187250
Thur  No      Dinner    0.159744
              Lunch     0.160311
      Yes     Lunch     0.163863
Name: tip_pct, dtype: float64

In [12]:
tips.groupby(["day", "smoker", "time"],as_index=False)[["tip_pct", "total_bill"]].mean()

     day smoker    time   tip_pct  total_bill
0    Fri     No  Dinner  0.139622   19.233333
1    Fri     No   Lunch  0.187735   15.980000
2    Fri    Yes  Dinner  0.165347   19.806667
3    Fri    Yes   Lunch  0.188937   12.323333
4    Sat     No  Dinner  0.158048   19.661778
5    Sat    Yes  Dinner  0.147906   21.276667
6    Sun     No  Dinner  0.160113   20.506667
7    Sun    Yes  Dinner  0.187250   24.120000
8   Thur     No  Dinner  0.159744   18.780000
9   Thur     No   Lunch  0.160311   17.075227
10  Thur    Yes   Lunch  0.163863   19.190588

In [13]:
tips

     total_bill   tip smoker   day    time  size   tip_pct
0         16.99  1.01     No   Sun  Dinner     2  0.059447
1         10.34  1.66     No   Sun  Dinner     3  0.160542
2         21.01  3.50     No   Sun  Dinner     3  0.166587
3         23.68  3.31     No   Sun  Dinner     2  0.139780
4         24.59  3.61     No   Sun  Dinner     4  0.146808
..          ...   ...    ...   ...     ...   ...       ...
239       29.03  5.92     No   Sat  Dinner     3  0.203927
240       27.18  2.00    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75     No   Sat  Dinner     2  0.098204
243       18.78  3.00     No  Thur  Dinner     2  0.159744

[244 rows x 7 columns]

In [14]:
tips.groupby("day")["tip_pct"].agg(["count", "mean", "median", "std"])

      count      mean    median       std
day
Fri      19  0.169913  0.155625  0.047665
Sat      87  0.153152  0.151832  0.051293
Sun      76  0.166897  0.161103  0.084739
Thur     62  0.161276  0.153846  0.038652

In [15]:
tips.groupby("day", as_index=False).agg(
        parties=("total_bill", "size"),
        average_bill=("total_bill", "mean"),
        median_tip_pct=("tip_pct", "median"),
        largest_party=("size", "max")
    )

    day  parties  average_bill  median_tip_pct  largest_party
0   Fri       19     17.151579        0.155625              4
1   Sat       87     20.441379        0.151832              5
2   Sun       76     21.410000        0.161103              6
3  Thur       62     17.682742        0.153846              6

In [17]:
tips.groupby("day").agg({
    "tip": ["max", ("med","median")],         
    "total_bill": "mean" 
})

        tip        total_bill
        max    med       mean
day
Fri    4.73  3.000  17.151579
Sat   10.00  2.750  20.441379
Sun    6.50  3.150  21.410000
Thur   6.70  2.305  17.682742

In [19]:
def peak_to_peak(values):
    return values.max() - values.min()

tips.groupby("day")["total_bill"].agg(
    bill_range=peak_to_peak
)

      bill_range
day
Fri        34.42
Sat        47.74
Sun        40.92
Thur       35.60

In [20]:
tips.groupby("day").agg({
    "tip": ["max", ("med","median")],         
    "total_bill": peak_to_peak
})

        tip          total_bill
        max    med peak_to_peak
day
Fri    4.73  3.000        34.42
Sat   10.00  2.750        47.74
Sun    6.50  3.150        40.92
Thur   6.70  2.305        35.60

In [21]:
tips.groupby("day")["total_bill"].agg(
    ["mean", "max", peak_to_peak]
)

           mean    max  peak_to_peak
day
Fri   17.151579  40.17         34.42
Sat   20.441379  50.81         47.74
Sun   21.410000  48.17         40.92
Thur  17.682742  43.11         35.60

In [23]:
tips.groupby(
    ["time", "smoker"],
    as_index=False
).agg(
    parties=("size", "size"),
    average_bill=("total_bill", "mean"),
    median_tip_pct=("tip_pct", "median"),
    maximum_size=("size", "max")
)

     time smoker  parties  average_bill  median_tip_pct  maximum_size
0  Dinner     No      106     20.095660        0.156249             6
1  Dinner    Yes       70     21.859429        0.149329             5
2   Lunch     No       45     17.050889        0.153492             6
3   Lunch    Yes       23     17.399130        0.154321             4

In [27]:
tips['day_mean_tip_pct'] = (
    tips.groupby("day")["tip_pct"]
    .transform("mean")
)

In [28]:
tips

,total_bill,tip,smoker,day,time,size,tip_pct,new_column,day_mean_tip_pct
0,16.99,1.01,No,Sun,Dinner,2,0.059447,0.166897,0.166897
1,10.34,1.66,No,Sun,Dinner,3,0.160542,0.166897,0.166897
2,21.01,3.50,No,Sun,Dinner,3,0.166587,0.166897,0.166897
3,23.68,3.31,No,Sun,Dinner,2,0.139780,0.166897,0.166897
4,24.59,3.61,No,Sun,Dinner,4,0.146808,0.166897,0.166897
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,No,Sat,Dinner,3,0.203927,0.153152,0.153152
240,27.18,2.00,Yes,Sat,Dinner,2,0.073584,0.153152,0.153152
241,22.67,2.00,Yes,Sat,Dinner,2,0.088222,0.153152,0.153152
242,17.82,1.75,No,Sat,Dinner,2,0.098204,0.153152,0.153152
243,18.78,3.00,No,Thur,Dinner,2,0.159744,0.161276,0.161276

In [29]:
(
    tips.groupby("day")["total_bill"]
    .transform(lambda x: (x - x.mean()) / x.std())
)

0     -0.500446
1     -1.253379
2     -0.045289
3      0.257016
4      0.360049
         ...
239    0.905933
240    0.710794
241    0.235076
242   -0.276505
243    0.139137
Name: total_bill, Length: 244, dtype: float64

In [30]:
example = tips.copy()

In [31]:
example.loc[[0, 10, 20], "tip"] = np.nan

In [33]:
(
    example["tip"]
    .fillna(
        example.groupby("day")["tip"]
        .transform("median")
    )
)

0      3.205
1      1.660
2      3.500
3      3.310
4      3.610
       ...
239    5.920
240    2.000
241    2.000
242    1.750
243    3.000
Name: tip, Length: 244, dtype: float64

In [34]:
example.loc[[10, 20, 30]]

,total_bill,tip,smoker,day,time,size,tip_pct,new_column,day_mean_tip_pct,tip_filled
10,10.27,NaN,No,Sun,Dinner,2,0.166504,0.166897,0.166897,3.205
20,17.92,NaN,No,Sat,Dinner,2,0.227679,0.153152,0.153152,2.735
30,9.55,1.45,No,Sat,Dinner,2,0.151832,0.153152,0.153152,1.450

In [37]:
tips.groupby(
    "day"
).filter(lambda group: len(group) >= 20)

     total_bill   tip smoker   day    time  size   tip_pct  day_mean_tip_pct
0         16.99  1.01     No   Sun  Dinner     2  0.059447          0.166897
1         10.34  1.66     No   Sun  Dinner     3  0.160542          0.166897
2         21.01  3.50     No   Sun  Dinner     3  0.166587          0.166897
3         23.68  3.31     No   Sun  Dinner     2  0.139780          0.166897
4         24.59  3.61     No   Sun  Dinner     4  0.146808          0.166897
..          ...   ...    ...   ...     ...   ...       ...               ...
239       29.03  5.92     No   Sat  Dinner     3  0.203927          0.153152
240       27.18  2.00    Yes   Sat  Dinner     2  0.073584          0.153152
241       22.67  2.00    Yes   Sat  Dinner     2  0.088222          0.153152
242       17.82  1.75     No   Sat  Dinner     2  0.098204          0.153152
243       18.78  3.00     No  Thur  Dinner     2  0.159744          0.161276

[225 rows x 8 columns]

In [38]:
def top_bills(group, n=3):
    return group.nlargest(n, "total_bill")

(
    tips.groupby("day", group_keys=True) 
    .apply(top_bills, include_groups=False)
)

          total_bill    tip smoker    time  size   tip_pct  day_mean_tip_pct
day
Fri  95        40.17   4.73    Yes  Dinner     4  0.117750          0.169913
     90        28.97   3.00    Yes  Dinner     2  0.103555          0.169913
     96        27.28   4.00    Yes  Dinner     2  0.146628          0.169913
Sat  170       50.81  10.00    Yes  Dinner     3  0.196812          0.153152
     212       48.33   9.00     No  Dinner     4  0.186220          0.153152
     59        48.27   6.73     No  Dinner     4  0.139424          0.153152
Sun  156       48.17   5.00     No  Dinner     6  0.103799          0.166897
     182       45.35   3.50    Yes  Dinner     3  0.077178          0.166897
     184       40.55   3.00    Yes  Dinner     2  0.073983          0.166897
Thur 197       43.11   5.00    Yes   Lunch     4  0.115982          0.161276
     142       41.19   5.00     No   Lunch     5  0.121389          0.161276
     85        34.83   5.17     No   Lunch     4  0.148435          0.161276

In [39]:
tip_pivot = pd.pivot_table(
    tips,
    values="tip_pct",
    index="day",
    columns="smoker",
    aggfunc="mean"
)

tip_pivot

smoker        No       Yes
day
Fri     0.151650  0.174783
Sat     0.158048  0.147906
Sun     0.160113  0.187250
Thur    0.160298  0.163863

In [40]:
renamed_pivot = tip_pivot.rename(columns={
    "No": "non_smoker",
    "Yes": "smoker"
})

renamed_pivot

smoker  non_smoker    smoker
day
Fri       0.151650  0.174783
Sat       0.158048  0.147906
Sun       0.160113  0.187250
Thur      0.160298  0.163863

In [41]:
mixed_agg_pivot = pd.pivot_table(
    tips,
    values=["total_bill", "tip"],
    index="day",
    aggfunc={"total_bill": ["mean", "max"], "tip": "median"}
)
mixed_agg_pivot

        tip total_bill
     median        max       mean
day
Fri   3.000      40.17  17.151579
Sat   2.750      50.81  20.441379
Sun   3.150      48.17  21.410000
Thur  2.305      43.11  17.682742

In [42]:
smoker_counts = pd.crosstab(
    tips["day"],
    tips["smoker"],
    margins=True
)
smoker_counts

smoker   No  Yes  All
day
Fri       4   15   19
Sat      45   42   87
Sun      57   19   76
Thur     45   17   62
All     151   93  244

In [43]:
day_lookup = pd.DataFrame({
    "day": ["Thur", "Fri", "Sat", "Sun"],
    "period": ["weekday", "weekday", "weekend", "weekend"]
})

tips_with_period = tips.merge(
    day_lookup,
    on="day",
    how="left",
    validate="many_to_one"
)

print(tips_with_period[["day", "total_bill", "tip", "period"]])

      day  total_bill   tip   period
0     Sun       16.99  1.01  weekend
1     Sun       10.34  1.66  weekend
2     Sun       21.01  3.50  weekend
3     Sun       23.68  3.31  weekend
4     Sun       24.59  3.61  weekend
..    ...         ...   ...      ...
239   Sat       29.03  5.92  weekend
240   Sat       27.18  2.00  weekend
241   Sat       22.67  2.00  weekend
242   Sat       17.82  1.75  weekend
243  Thur       18.78  3.00  weekday

[244 rows x 4 columns]

In [44]:
visits = pd.DataFrame({
    "day": pd.Categorical(
        ["Mon", "Mon", "Tue"],
        categories=["Mon", "Tue", "Wed"]
    )
})

print(visits.groupby("day", observed=True).size())

day
Mon    2
Tue    1
dtype: int64